// Builds the whole profile: every SVG in assets/profile/ (light + dark) and
// README.md itself, from scripts/profile/data.mjs.
//
//   node scripts/build-profile.mjs
//
// No dependencies and no network. The activity card and snake are separate:
// they need live data and are built by .github/workflows/profile-assets.yml.

import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { THEMES } from './profile/kit.mjs';
import * as C from './profile/components.mjs';
import * as D from './profile/data.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = 'assets/profile';
rmSync(join(root, OUT), { recursive: true, force: true });
const write = (rel, s) => {
  mkdirSync(dirname(join(root, rel)), { recursive: true });
  writeFileSync(join(root, rel), s);
};
const themed = (name, fn) => { for (const t of Object.values(THEMES)) write(`${OUT}/${name}-${t.name}.svg`, fn(t)); };

// ── assets ──
themed('hero', C.hero);
themed('counters', C.counters);
themed('about', C.neofetch);
themed('experience', C.experience);
themed('research', C.research);
themed('certifications', C.certs);
themed('skills', C.skills);
themed('marquee', C.marquee);
themed('footer', C.footer);
themed('interview-coach-art', C.interviewArt);
for (const p of D.flagships) themed(`flagship-${p.id}`, (t) => C.flagship(t, p));
for (const p of D.projects) themed(`card-${p.id}`, (t) => C.projectCard(t, p));
for (const b of C.BUTTONS) write(`${OUT}/buttons/${b.file}.svg`, C.button(b));

const SECTIONS = [
  ['about', '01', 'About me', 'who I am'],
  ['experience', '02', 'Experience', 'where I work and what shipped'],
  ['flagships', '03', 'Flagship projects', 'deployed, measured, open-sourced'],
  ['projects', '04', 'More projects', 'AI, speech, vision, games'],
  ['research', '05', 'Research & patent', 'published and peer-reviewed'],
  ['certifications', '06', 'Certifications', 'cloud and ML'],
  ['stack', '07', 'Tech stack', 'what I ship with'],
  ['activity', '08', 'GitHub analytics', 'live, refreshed daily'],
  ['dsa', '09', 'Problem solving', 'LeetCode and NeetCode'],
];
for (const [id, num, title, sub] of SECTIONS) themed(`header-${id}`, (t) => C.header(t, num, title, sub));

// ── README ──
const pic = (name, alt, { width = '100%', href, remote } = {}) => {
  const src = (th) => (remote ? remote(th) : `${OUT}/${name}-${th}.svg`);
  const inner = `<picture>
  <source media="(prefers-color-scheme: dark)" srcset="${src('dark')}">
  <source media="(prefers-color-scheme: light)" srcset="${src('light')}">
  <img alt="${alt.replace(/"/g, '&quot;')}" src="${src('dark')}" width="${width}">
</picture>`;
  return href ? `<a href="${href}">${inner}</a>` : inner;
};
const header = (id) => {
  const [, num, title, sub] = SECTIONS.find((s) => s[0] === id);
  return `\n<br>\n\n${pic(`header-${id}`, `${num} ${title}: ${sub}`)}\n`;
};
const btn = (file, href, alt) => `<a href="${href}"><img src="${OUT}/buttons/${file}.svg" alt="${alt}" height="38"></a>`;
const ext = (url) => url; // external widgets pass through as-is

let md = `<!--
  GENERATED by scripts/build-profile.mjs from scripts/profile/data.mjs.
  Edit the data or the components, then run: node scripts/build-profile.mjs
  Activity card + snake come from the \`output\` branch (.github/workflows/profile-assets.yml).
-->

${pic('hero', `${D.person.name}: ${D.person.title}. ${D.person.tagline}`, { href: D.person.portfolio })}

<p align="center">
  ${btn('portfolio', D.person.portfolio, 'Portfolio')}
  ${btn('resume', D.person.resume, 'Resume')}
  ${btn('linkedin', D.person.linkedin, 'LinkedIn')}
  ${btn('email', `mailto:${D.person.email}`, 'Email')}
  ${btn('leetcode', D.person.leetcode, 'LeetCode')}
  ${btn('instagram', D.person.instagram, 'Instagram')}
</p>

${pic('counters', D.headline.map((h) => `${h.value} ${h.label} (${h.sub})`).join('; '))}
${header('about')}
${pic('about', D.neofetch.map(([k, v]) => `${k}: ${v}`).join('; '))}
${header('experience')}
${pic('experience', D.experience.map((e) => `${e.role} at ${e.company}, ${e.period}. ${e.impact.join(' ')}`).join(' '))}
${header('flagships')}
Each of these runs in production from a private codebase. The linked repositories are public **showcases** I extracted from them: the UI, the tests and the tooling, runnable in one command, with the proprietary logic swapped for a mock behind the same interface. Every number was measured, not estimated.
`;

for (const p of D.flagships) {
  const artName = p.art === 'interview-coach' ? 'interview-coach-art' : null;
  const art = artName
    ? pic(artName, `${p.title} illustration`, { href: p.code })
    : `<a href="${p.live ?? p.code}"><picture>
  <source media="(prefers-color-scheme: dark)" srcset="assets/projects/${p.art}-dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="assets/projects/${p.art}-light.svg">
  <img alt="${p.title} banner" src="assets/projects/${p.art}-dark.svg" width="100%">
</picture></a>`;
  const buttons = [
    p.live && btn('live', p.live, `${p.title} live demo`),
    btn('source', p.code, `${p.title} source code`),
    p.extra && btn(p.extra[0] === 'Playground' ? 'playground' : 'coach-ui', p.extra[1], `${p.title} ${p.extra[0]}`),
  ].filter(Boolean).join('\n  ');
  const panelAlt = `${p.title}. ${p.desc} ` + (p.metrics
    ? p.metrics.map(([l, b, a, u]) => `${l}: ${b}${u ? ' ' + u : ''} to ${a}${u ? ' ' + u : ''}`).join('; ')
    : p.facts.map(([v, l]) => `${v} ${l}`).join('; ')) + `. Stack: ${p.stack.join(', ')}.`;
  md += `
<br>

${art}

${pic(`flagship-${p.id}`, panelAlt, { href: p.live ?? p.code })}

<p align="center">
  ${buttons}
</p>

<details>
<summary><b>▶ Watch the ${p.title} walkthrough</b></summary>
<br>
<p align="center"><img src="${p.gif}" alt="${p.title} walkthrough" width="100%"></p>
</details>
`;
}

md += header('projects') + '\n<p align="center">\n';
D.projects.forEach((p) => {
  md += `${pic(`card-${p.id}`, `${p.title}: ${p.desc} Built with ${p.stack.join(', ')}.`, { width: '49%', href: p.url })}\n`;
});
const rl = D.projects.find((p) => p.links);
md += `</p>

<p align="center"><sub>Reinforcement-learning trio: ${rl.links.map(([l, u]) => `<a href="${u}">${l}</a>`).join(' · ')}</sub></p>
${header('research')}
${pic('research', `Publications: ${D.publications.map((p) => `${p.title} (${p.badge})`).join('; ')}. Patent: ${D.patent.title}, application #${D.patent.number}, ${D.patent.office}.`)}
${header('certifications')}
${pic('certifications', D.certifications.map((c) => `${c.name}, ${c.provider}`).join('; '))}
${header('stack')}
${pic('marquee', D.marquee.flat().join(', '))}

${pic('skills', D.skills.map((g) => `${g.label}: ${g.items.map(([n, l]) => `${n} (${l}/5)`).join(', ')}`).join('; '))}

<p align="center">
${[
  ['py,ts,js,cs,cpp,java,solidity,html,css', 'Python, TypeScript, JavaScript, C#, C++, Java, Solidity, HTML, CSS'],
  ['react,nextjs,angular,vite,tailwind,threejs,nodejs,express,dotnet,flask,fastapi', 'React, Next.js, Angular, Vite, Tailwind, Three.js, Node.js, Express, .NET, Flask, FastAPI'],
  ['postgres,mongodb,redis,firebase,azure,aws,gcp,docker,kubernetes,terraform,githubactions,vercel', 'PostgreSQL, MongoDB, Redis, Firebase, Azure, AWS, Google Cloud, Docker, Kubernetes, Terraform, GitHub Actions, Vercel'],
  ['pytorch,tensorflow,sklearn,opencv,unity,unreal,godot,blender,linux,git,figma,postman', 'PyTorch, TensorFlow, scikit-learn, OpenCV, Unity, Unreal, Godot, Blender, Linux, Git, Figma, Postman'],
].map(([i, alt]) => `  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://skillicons.dev/icons?i=${i}&theme=dark&perline=12">
    <img alt="${alt}" src="https://skillicons.dev/icons?i=${i}&theme=light&perline=12">
  </picture>`).join('\n  <br>\n')}
</p>
${header('activity')}
${pic('stats', 'GitHub activity: contributions over the last 12 months, current and longest streak, public repositories and stars, weekly contributions and top languages.', { remote: (th) => `https://raw.githubusercontent.com/${D.person.handle}/${D.person.handle}/output/stats-${th}.svg` })}

<p align="center">
${pic('streak', 'GitHub contribution streak', { width: '49%', remote: (th) => ext(`https://streak-stats.demolab.com?user=${D.person.handle}&hide_border=true&card_width=560&theme=${th === 'dark' ? 'github-dark-blue' : 'default'}&ring=${th === 'dark' ? 'A78BFA' : '6D28D9'}&fire=${th === 'dark' ? '22D3EE' : '0E7490'}&currStreakLabel=${th === 'dark' ? 'A78BFA' : '6D28D9'}`) })}
${pic('trophy', 'GitHub trophies', { width: '49%', remote: (th) => ext(`https://github-profile-trophy.vercel.app/?username=${D.person.handle}&theme=${th === 'dark' ? 'onedark' : 'flat'}&no-frame=true&no-bg=true&row=2&column=3&margin-w=6&margin-h=6`) })}
</p>

${pic('activity-graph', 'Contribution activity graph', { remote: (th) => ext(`https://github-readme-activity-graph.vercel.app/graph?username=${D.person.handle}&hide_border=true&area=true&radius=16&${th === 'dark' ? 'bg_color=0d1117&color=a78bfa&line=22d3ee&point=e6edf3&area_color=a78bfa' : 'bg_color=ffffff&color=6d28d9&line=0e7490&point=1f2328&area_color=6d28d9'}`) })}

${pic('snake', 'A snake eating the contribution graph from the last year.', { remote: (th) => `https://raw.githubusercontent.com/${D.person.handle}/${D.person.handle}/output/snake-${th}.svg` })}
${header('dsa')}
I take part in LeetCode contests regularly, in C++ and Python, and every accepted [NeetCode solution](${D.GH}/neetcode-submissions) syncs to GitHub automatically.

${pic('leetcode', 'LeetCode stats for Kashyap_patel26: problems solved by difficulty, contest rating and submission heatmap.', { href: D.person.leetcode, remote: (th) => ext(`https://leetcard.jacoblin.cool/Kashyap_patel26?theme=${th}&font=Inter&ext=contest&border=0&radius=16`) })}

<br>

${pic('footer', `Thanks for stopping by. ${D.person.tagline} ${D.person.email}`, { href: `mailto:${D.person.email}` })}

<p align="center">
  <img src="https://komarev.com/ghpvc/?username=${D.person.handle}&style=flat-square&color=7c3aed&label=profile+views" alt="Profile views">
</p>
`;

write('README.md', md);
console.log(`wrote ${OUT}/ and README.md`);
